import { Bell, Check, ChevronRight, Command, FileImage, ImageIcon, MoreHorizontal, Paperclip, Play, Plus, Search, Settings, Sparkles, Upload, Video } from "lucide-react";
import {
  AIComposer, Badge, Button, Card, Checkbox, CommandPalette, DialogSurface, DropdownMenu, DropdownMenuItem, EmptyState, Field, FilterChip, FloatingToolbar, IconButton, Input, InspectorPanel, MediaCard, MetricCard, Pagination, Popover, Progress, ProjectCard, Radio, SearchField, SegmentedControl, Select, SheetSurface, Skeleton, StatusBadge, StatusIndicator, Switch, Table, Tabs, Tag, TemplateCard, Textarea, Toast, TooltipHint, UploadZone, WorkspaceSwitcher
} from "@creatye/ui";

const tabs = [{value:"foundations",label:"Foundations"},{value:"components",label:"Components"},{value:"patterns",label:"Patterns"}] as const;
const tableRows = [["Quiz reel",<StatusIndicator key="a" label="Ready" intent="success" />,"22 Sep"],["Creator notes",<StatusIndicator key="b" label="Rendering" intent="brand" pulse />,"22 Sep"]] as const;

function Section({ index, title, description, children }: { index: string; title: string; description: string; children: React.ReactNode }) {
  return <section className="canvas-ds-section"><header><span>{index}</span><div><h2>{title}</h2><p>{description}</p></div></header><div className="canvas-ds-section__body">{children}</div></section>;
}

export function DesignSystemPlayground() {
  return <div className="canvas-design-system">
    <header className="canvas-ds-head"><div><span>Creatye Studio</span><h1>Creatye Canvas</h1><p>Spatial, quiet, and precise foundations for a professional creative operation.</p></div><Tabs items={tabs} active="foundations" ariaLabel="Design system sections" /></header>

    <Section index="01" title="Semantic color" description="Warm neutrals, black primary actions, and color only when it carries meaning."><div className="canvas-swatches">{["background","canvas","surface","surface-raised","surface-muted","surface-selected","foreground","foreground-secondary","foreground-muted","border","primary","accent","success","warning","danger","overlay","focus"].map((token) => <div key={token} style={{background:`var(--cr-${token})`}}><span>{token}</span><code>--cr-{token}</code></div>)}</div><div className="canvas-theme-pair"><div><strong>Light</strong><span>Warm spatial canvas</span></div><div data-theme="dark"><strong>Dark</strong><span>Layered neutral surfaces</span></div></div></Section>

    <Section index="02" title="Typography, spacing, and depth" description="Geist Sans for interface language; Geist Mono for exact values and system data."><div className="canvas-type-spec"><div><span>Display</span><strong className="canvas-type-display">Create with clarity.</strong><code>32 / 38 / 620</code></div><div><span>Heading</span><strong className="canvas-type-heading">Publishing performance</strong><code>20 / 26 / 600</code></div><div><span>Body</span><strong>Quiet hierarchy supports dense creative work.</strong><code>14 / 21 / 400</code></div><div><span>Mono</span><strong className="canvas-type-mono">00:14:23 · 1080×1920</strong><code>12 / 18 / 500</code></div></div><div className="canvas-token-bars">{[4,8,12,16,24,32,40,48,64].map((value)=><span key={value} style={{width:value*2}}><i />{value}</span>)}</div><div className="canvas-radius-row">{[4,8,12,16,22,28].map((value)=><span key={value} style={{borderRadius:value}}>{value}</span>)}</div></Section>

    <Section index="03" title="Controls and states" description="All controls support disabled, loading, error, hover, and visible keyboard focus."><div className="canvas-control-groups"><div><span>Buttons</span><div><Button variant="primary">Primary</Button><Button variant="secondary">Secondary</Button><Button variant="accent">AI action</Button><Button variant="quiet">Quiet</Button><Button variant="danger">Danger</Button><Button loading>Loading</Button><Button disabled>Disabled</Button><IconButton label="Notifications" variant="surface"><Bell size={15}/></IconButton></div></div><div><span>Selection</span><div><SegmentedControl items={tabs} active="components" ariaLabel="Example segmented control"/><FilterChip aria-pressed="true">Active</FilterChip><FilterChip>Draft</FilterChip><Badge intent="brand">Beta</Badge><StatusBadge intent="success">Healthy</StatusBadge><Tag>Template</Tag></div></div><div><span>Inputs</span><div className="canvas-input-grid"><Field label="Name"><Input defaultValue="Creator growth"/></Field><Field label="Search"><SearchField placeholder="Find media"/></Field><Field label="Page"><Select options={[{value:"br",label:"Creatye Brasil"},{value:"all",label:"All pages"}]}/></Field><Field label="Email" error="Use a valid workspace email"><Input aria-invalid defaultValue="creator@"/></Field><Field label="Caption"><Textarea defaultValue="A clear creator workflow."/></Field><div><Switch label="Auto-save" defaultChecked/><label><Checkbox defaultChecked/> Compact density</label><label><Radio name="density" defaultChecked/> Comfortable</label></div></div></div></div></Section>

    <Section index="04" title="Surfaces and feedback" description="Broad soft elevation is reserved for floating and interruptive surfaces."><div className="canvas-surface-grid"><Card><h3>Card</h3><p>Normal flow relies on surface contrast and hairlines.</p></Card><Popover title="Popover"><strong>Workspace actions</strong><Button variant="quiet" size="sm">Open settings</Button></Popover><DropdownMenu label="Example menu"><DropdownMenuItem><FileImage size={14}/>Open media</DropdownMenuItem><DropdownMenuItem><Settings size={14}/>Settings</DropdownMenuItem></DropdownMenu><DialogSurface title="Dialog preview"><h3>Publish batch?</h3><p>Three videos are ready for review.</p><Button variant="primary">Continue</Button></DialogSurface><SheetSurface title="Drawer preview"><h3>Mobile drawer</h3><p>Touch-friendly contextual controls.</p></SheetSurface><div className="canvas-feedback-stack"><Toast intent="success"><Check size={14}/>Saved successfully</Toast><Toast intent="danger">Rendering failed</Toast><TooltipHint>Keyboard shortcut · ⌘K</TooltipHint><Progress value={68} label="Usage"/><Skeleton/></div></div></Section>

    <Section index="05" title="Cards, data, and media" description="Media-first cards and quiet operational data patterns share the same semantics."><div className="canvas-component-grid"><ProjectCard title="September campaign" meta="Updated 12 min ago" preview={<div className="canvas-project-preview"><ImageIcon size={24}/></div>} action={<IconButton label="Project menu" size="sm"><MoreHorizontal size={14}/></IconButton>}/><MetricCard label="Reach" value="428.6k" detail="Last 7 days" trend={<span className="canvas-positive">+18.4%</span>}/><MediaCard title="Opening hook" meta="00:08 · 9:16" selected media={<div className="canvas-project-preview"><Play size={24}/></div>}/><TemplateCard title="Bold hook" category="Growth · 9:16" selected preview={<div className="canvas-template-demo"><b>HOOK</b></div>}/></div><Table caption="Recent content" columns={["Content","Status","Updated"]} rows={tableRows}/><Pagination current={1} total={4}/></Section>

    <Section index="06" title="Creation patterns" description="AI, upload, command, inspection, and floating tools remain contextual and restrained."><div className="canvas-creation-grid"><AIComposer actions={<><IconButton label="Attach" size="sm"><Paperclip size={14}/></IconButton><IconButton label="Creative tools" size="sm"><Sparkles size={14}/></IconButton></>}/><UploadZone title="Drop media here" description="Video, image, or audio up to 2 GB" action={<Button variant="secondary"><Upload size={14}/>Browse files</Button>}/><CommandPalette><DropdownMenuItem><Search size={14}/>Search content</DropdownMenuItem><DropdownMenuItem><Plus size={14}/>Create project</DropdownMenuItem><DropdownMenuItem><Command size={14}/>Open command center</DropdownMenuItem></CommandPalette><InspectorPanel title="Inspector" footer={<Button variant="primary">Apply</Button>}><Field label="Format"><Select options={[{value:"9:16",label:"Vertical · 9:16"}]}/></Field><Switch label="Safe area" defaultChecked/></InspectorPanel><FloatingToolbar><IconButton label="Video"><Video size={15}/></IconButton><IconButton label="Image"><ImageIcon size={15}/></IconButton><IconButton label="More"><MoreHorizontal size={15}/></IconButton></FloatingToolbar><EmptyState title="Nothing shared yet" description="Shared projects will appear here." action={<Button variant="secondary">Browse projects <ChevronRight size={14}/></Button>}/></div></Section>

    <Section index="07" title="Responsive calibration" description="Desktop, half-ultrawide, tablet, and mobile preserve hierarchy without horizontal overflow."><div className="canvas-device-grid"><div className="canvas-device canvas-device--desktop"><WorkspaceSwitcher mark="C" name="Creatye Studio" meta="Workspace"/><div><span/><span/><span/></div></div><div className="canvas-device canvas-device--half"><span className="canvas-device-rail">C</span><div><span/><span/><span/></div></div><div className="canvas-device canvas-device--mobile"><header><b>C</b><i/></header><div><span/><span/><span/></div><footer/></div></div></Section>
  </div>;
}
