"use client";

import { useState } from "react";
import { BookOpen, ChevronDown, ChevronRight, LifeBuoy, MessageCircle, Send, Video } from "lucide-react";
import { Button } from "@creatye/ui";
import { ProductModal, ProductNotice, ProductPage } from "@/components/product/product-ui";

const articles=[{title:"Conectar uma página do Instagram",category:"Páginas",detail:"Permissões, requisitos e sincronização."},{title:"Criar sua primeira automação",category:"Automações",detail:"Do gatilho à publicação do fluxo."},{title:"Produzir um vídeo no Studio",category:"Studio",detail:"Seleção, personalização e revisão."},{title:"Programar publicações",category:"Conteúdo",detail:"Calendário, horários e rascunhos."},{title:"Entender métricas e conversões",category:"Analytics",detail:"Como ler tendências e comparar períodos."},{title:"Gerenciar equipe e acessos",category:"Conta",detail:"Papéis, convites e segurança."}];
const faqs=["Como funcionam os créditos?","Posso conectar mais de uma página?","Como recuperar uma automação pausada?","Quais formatos de mídia são aceitos?"];
export function HelpProduct(){const[open,setOpen]=useState(0);const[contact,setContact]=useState(false);const[notice,setNotice]=useState("");return <ProductPage eyebrow="Suporte" title="Como podemos ajudar?" description="Encontre orientações rápidas ou fale com nossa equipe." actions={<Button variant="primary" onClick={()=>setContact(true)}><MessageCircle size={14}/> Falar com suporte</Button>}><div className="help-categories">{[{icon:BookOpen,title:"Primeiros passos",detail:"Configure seu workspace"},{icon:Video,title:"Studio",detail:"Produza e publique"},{icon:LifeBuoy,title:"Solução de problemas",detail:"Resolva rapidamente"}].map(({icon:Icon,title,detail})=><button type="button" key={title}><Icon size={19}/><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={15}/></button>)}</div><section className="help-layout"><div className="product-panel"><header><h2>Artigos recomendados</h2><span className="product-muted">{articles.length} resultados</span></header><div className="product-panel-body help-articles">{articles.map((item)=><button type="button" key={item.title}><span>{item.category}</span><strong>{item.title}</strong><small>{item.detail}</small><ChevronRight size={14}/></button>)}</div></div><aside className="product-panel"><header><h2>Perguntas frequentes</h2></header><div className="product-panel-body help-faq">{faqs.map((item,index)=><article key={item}><button type="button" onClick={()=>setOpen(open===index?-1:index)}><strong>{item}</strong><ChevronDown size={14}/></button>{open===index?<p>Você encontra essa opção nas configurações da área correspondente. As ações desta versão usam dados simulados e estão prontas para a integração futura.</p>:null}</article>)}</div></aside></section>{contact?<ProductModal title="Falar com o suporte" description="Conte o que aconteceu e retornaremos por e-mail." onClose={()=>setContact(false)} footer={<><Button variant="quiet" onClick={()=>setContact(false)}>Cancelar</Button><Button variant="primary" onClick={()=>{setContact(false);setNotice("Mensagem enviada para o suporte.")}}><Send size={13}/> Enviar mensagem</Button></>}><label className="product-field">Assunto<select><option>Dúvida de uso</option><option>Problema técnico</option><option>Cobrança</option><option>Sugestão</option></select></label><label className="product-field">Mensagem<textarea placeholder="Descreva sua dúvida com o máximo de contexto possível."/></label><label className="product-check"><input type="checkbox" defaultChecked/> Incluir informações do navegador</label></ProductModal>:null}{notice?<ProductNotice onClose={()=>setNotice("")}>{notice}</ProductNotice>:null}</ProductPage>}
