"use client";

import { useState } from "react";
import { Download, ImagePlus, MoreHorizontal, Plus, Sparkles, WandSparkles } from "lucide-react";
import { Button, IconButton } from "@creatye/ui";
import { ProductDrawer, ProductNotice, ProductPage, ProductTabs } from "@/components/product/product-ui";

const imageIdeas = ["Campanha editorial", "Produto em destaque", "Retrato lifestyle", "Anúncio minimalista", "Capa de carrossel", "Quote visual"];

export function ImageStudioProduct() {
  const [tab,setTab]=useState("create");
  const [prompt,setPrompt]=useState("Retrato editorial de uma criadora em um café contemporâneo, luz natural suave, composição clean e premium");
  const [generated,setGenerated]=useState([0,1,2,3]);
  const [selected,setSelected]=useState<number|null>(null);
  const [notice,setNotice]=useState("");
  function generate(){setGenerated((items)=>[...items,items.length,items.length+1]);setNotice("Duas novas variações foram geradas.");}
  return <ProductPage eyebrow="Image Studio" title="Crie imagens para sua próxima campanha" description="Gere, refine e exporte peças visuais mantendo a identidade do seu conteúdo." actions={<Button variant="primary" onClick={generate}><Sparkles size={14}/> Gerar imagens</Button>}>
    <ProductTabs items={[{id:"create",label:"Criar"},{id:"projects",label:"Projetos",count:6},{id:"favorites",label:"Favoritos",count:3}]} active={tab} onChange={setTab}/>
    {tab==="create"?<div className="image-studio-layout"><section className="product-panel image-prompt-panel"><header><h2>Descreva a imagem</h2><span className="product-muted">Crédito estimado: 2</span></header><div className="product-panel-body image-prompt-form"><label className="product-field">Prompt<textarea value={prompt} onChange={(event)=>setPrompt(event.target.value)}/></label><div className="image-idea-chips">{imageIdeas.map((idea)=><button type="button" key={idea} onClick={()=>setPrompt(idea)}>{idea}</button>)}</div><div className="image-options"><label className="product-field">Formato<select><option>4:5 · Feed</option><option>9:16 · Story</option><option>1:1 · Quadrado</option></select></label><label className="product-field">Estilo<select><option>Editorial</option><option>Natural</option><option>Produto</option><option>Ilustração</option></select></label><label className="product-field">Variações<select><option>4 imagens</option><option>2 imagens</option></select></label></div><Button variant="primary" onClick={generate}><WandSparkles size={14}/> Gerar variações</Button></div></section><section className="image-results"><header><div><h2>Variações</h2><p>Clique em uma imagem para ajustar ou exportar.</p></div><Button size="sm" onClick={()=>setGenerated([])}>Limpar</Button></header><div>{generated.length?generated.map((item)=><article key={item}><button type="button" className={`generated-image generated-image--${item%6}`} onClick={()=>setSelected(item)}><span>CREATYE</span><strong>{["IDEIAS QUE MOVEM","CONTEÚDO COM INTENÇÃO","CRIE O PRÓXIMO PASSO","SUA MARCA EM FOCO"][item%4]}</strong></button><footer><span>Variação {item+1}</span><IconButton label="Baixar" size="sm" onClick={()=>setNotice("Imagem preparada para download.")}><Download size={14}/></IconButton><IconButton label="Mais opções" size="sm"><MoreHorizontal size={14}/></IconButton></footer></article>):<button className="image-empty-result" type="button" onClick={generate}><ImagePlus size={23}/><strong>Gere suas primeiras variações</strong><span>As imagens aparecerão aqui.</span></button>}</div></section></div>:<div className="image-project-grid">{["Campanha setembro","Lançamento Academy","Editorial Creatye","Capas semanais","Oferta verão","Retratos fundadores"].map((item,index)=><article key={item}><div className={`generated-image generated-image--${index}`}><strong>{item}</strong></div><footer><div><strong>{item}</strong><small>{index+3} imagens · editado ontem</small></div><IconButton label="Abrir"><MoreHorizontal size={14}/></IconButton></footer></article>)}</div>}
    {selected!==null?<ProductDrawer title={`Variação ${selected+1}`} subtitle="4:5 · 1080 × 1350 px" onClose={()=>setSelected(null)} footer={<><Button><Download size={14}/> Baixar</Button><Button variant="primary" onClick={()=>setNotice("Imagem adicionada ao projeto.")}><Plus size={14}/> Usar no projeto</Button></>}><div className={`generated-image generated-image--${selected%6} generated-image--large`}><span>CREATYE</span><strong>CONTEÚDO COM INTENÇÃO</strong></div><label className="product-field">Ajuste rápido<textarea defaultValue={prompt}/></label><div className="image-options"><label className="product-field">Contraste<input type="range" defaultValue="58"/></label><label className="product-field">Saturação<input type="range" defaultValue="46"/></label></div></ProductDrawer>:null}{notice?<ProductNotice onClose={()=>setNotice("")}>{notice}</ProductNotice>:null}
  </ProductPage>;
}
