import Image from "next/image";
import Link from "next/link";
import { Captions, Check, ChevronDown, ChevronRight, Filter, ImageIcon, LayoutTemplate, Music2, Play, Search, SlidersHorizontal, Type, X } from "lucide-react";
import { Button, StatusBadge } from "@creatye/ui";
import { MobileShell } from "../mobile-shell";

export type MobileView = "select" | "customize" | "templates" | "publish" | "history";
const media = [["Sara Novo", "creator-home.png"], ["Cecilia Novo", "creator-cafe.png"], ["Jamilly novo", "creator-skincare.png"], ["Xanaina Novo", "creator-home.png"], ["Cibelle PT", "creator-cafe.png"], ["Bianca G2", "creator-skincare.png"]] as const;

function MobilePreview() { return <div className="mobile-preview"><Image src="/media/creator-home.png" alt="Creator video preview" fill priority sizes="300px" /><div className="mobile-template-overlay"><strong>3 ways to grow</strong><span>your audience today</span></div><button aria-label="Play preview"><Play size={18} fill="currentColor" /></button><div className="mobile-preview-progress"><span /><i>80%</i></div></div>; }

function SelectView() { return <MobileShell step={1}><section className="mobile-select"><div className="mobile-search-row"><label><Search size={16} /><input placeholder="Search videos, pages, tags" /></label><button aria-label="Filter"><Filter size={16} /></button></div><div className="mobile-page-chips"><button className="is-active">Library</button><button>victor@creatye.com</button><button>quizse79@gmail.com</button></div><div className="mobile-media-grid">{media.map(([title, src], index) => <button key={`${title}-${index}`} className={index < 4 ? "is-selected" : ""}><Image src={`/media/${src}`} alt="" fill sizes="46vw" /><span className="mobile-media-check">{index < 4 ? <Check size={13} /> : null}</span><span><small>9:16 / 3.8 MB</small><strong>{title}</strong><em>#page &nbsp; #base</em></span></button>)}</div><Link className="mobile-sticky-action" href="/mobile?view=customize">Continue with 4 <ChevronRight size={16} /></Link></section></MobileShell>; }

function CustomizeView() { const tools = [{ label: "Template", icon: LayoutTemplate }, { label: "Text", icon: Type }, { label: "Image", icon: ImageIcon }, { label: "Layout", icon: SlidersHorizontal }, { label: "Audio", icon: Music2 }]; return <MobileShell step={2}><section className="mobile-customize"><div className="mobile-preview-wrap"><MobilePreview /></div><p className="mobile-preview-meta">Live preview / B / 4 videos</p><div className="mobile-tool-tray">{tools.map((tool, index) => { const Icon = tool.icon; return <Link key={tool.label} href={index === 0 ? "/mobile?view=templates" : "#"} className={index === 3 ? "is-active" : ""}><Icon size={18} /><span>{tool.label}</span></Link>; })}</div><Link className="mobile-next-action" href="/mobile?view=publish">Continue to publish <ChevronRight size={17} /></Link></section></MobileShell>; }

function TemplatesView() { return <MobileShell step={2}><div className="mobile-template-backdrop"><MobilePreview /></div><section className="mobile-template-sheet"><span className="sheet-handle" /><header><Link href="/mobile?view=customize"><ChevronRight size={18} /></Link><strong>Templates</strong><Link href="/mobile?view=customize"><X size={18} /></Link></header><label><Search size={16} /><input placeholder="Search templates" /></label><div className="mobile-template-tabs"><button>All</button><button>Captions</button><button className="is-active">Overlay</button><button>Video</button></div><div className="mobile-template-selects"><button>All categories <ChevronDown size={13} /></button><button>All niches <ChevronDown size={13} /></button></div><div className="mobile-template-grid">{["QUIZ", "HOOK", "LIST", "POV", "GUIDE", "DUEL"].map((name, index) => <button key={name} className={index === 1 ? "is-selected" : ""}><span className={`template-art template-art--${index}`}><b>{name}</b><i>{index % 2 ? "3 steps" : "NEW POST"}</i></span><strong>{["Clean quiz", "Bold hook", "Fast list", "POV caption", "Mini guide", "Before / after"][index]}</strong><small>Overlay</small>{index === 1 ? <em><Check size={12} /></em> : null}</button>)}</div></section></MobileShell>; }

function PublishView() { return <MobileShell step={3}><section className="mobile-publish"><header><span>Final step</span><h1>Ready to publish</h1><p>4 videos use one caption and three destinations.</p></header><div className="mobile-publish-preview"><div><Image src="/media/creator-home.png" alt="" fill sizes="112px" /></div><span><strong>Creator growth batch</strong><small>4 videos / 1 template</small><StatusBadge intent="success">Ready</StatusBadge></span></div><button><span>IG</span><i><strong>Creatye Brasil</strong><small>Instagram / @creatyebrasil</small></i><ChevronRight size={16} /></button><button><Captions size={17} /><i><strong>Caption ready</strong><small>126 characters / 2 hashtags</small></i><ChevronRight size={16} /></button><div className="mobile-publish-time"><button className="is-active">Now</button><button>Schedule</button></div><Button variant="primary" size="lg">Publish 4 videos <ChevronRight size={17} /></Button></section></MobileShell>; }

function HistoryView() { return <MobileShell active="History"><section className="mobile-history"><label><Search size={16} /><input placeholder="Search batches" /></label><div className="mobile-history-filters"><button className="is-active">All</button><button>Processing</button><button>Queued</button><button>Scheduled</button></div>{["18:18", "17:42", "16:05"].map((time, index) => <article key={time}><header><div><strong>Batch 18/09/2026</strong><span>{index === 0 ? "Bucket" : "Instagram reels"}</span></div><StatusBadge intent="success">Completed</StatusBadge></header><b>admin@creatye.com / Master Workspace</b><p>Rendering and publishing completed.</p><div><span>4 videos</span><span>4 posts</span><time>{time}</time><span>0 errors</span></div><i><span /></i><em>100%</em></article>)}</section></MobileShell>; }

export function MobileCalibration({ view }: { view: MobileView }) { if (view === "select") return <SelectView />; if (view === "templates") return <TemplatesView />; if (view === "publish") return <PublishView />; if (view === "history") return <HistoryView />; return <CustomizeView />; }
