"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Download, History, ImagePlus, MonitorPlay, Play, Plus, Upload, WandSparkles } from "lucide-react";
import { Button, IconButton } from "@creatye/ui";
import { connectedPages, studioProjects, templateFixtures } from "@/lib/product-fixtures";
import { ProductModal, ProductNotice, ProductPage } from "@/components/product/product-ui";

export type StudioStep = "select" | "customize" | "review" | "publish" | "history";
const steps: readonly { id: StudioStep; label: string }[] = [{ id: "select", label: "Selecionar" }, { id: "customize", label: "Personalizar" }, { id: "review", label: "Revisar" }, { id: "publish", label: "Publicar" }];

function StudioStepper({ current }: { current: StudioStep }) { const currentIndex = Math.max(0, steps.findIndex((item) => item.id === current)); return <nav className="studio-stepper" aria-label="Etapas do Studio">{steps.map((item,index) => <Link key={item.id} href={`/studio?step=${item.id}`} data-state={index < currentIndex ? "done" : index === currentIndex ? "active" : "next"}><span>{index < currentIndex ? <Check size={11} /> : index + 1}</span>{item.label}</Link>)}</nav>; }

export function StudioProduct({ step }: { step: StudioStep }) {
  const [selectedMedia, setSelectedMedia] = useState(["Sara Novo", "Cecilia Novo"]);
  const [selectedTemplate, setSelectedTemplate] = useState(templateFixtures[0]!.id);
  const [notice, setNotice] = useState("");
  const [uploadOpen, setUploadOpen] = useState(false);
  return <ProductPage eyebrow="Video Studio" title="Crie uma campanha completa" description="Escolha os materiais, ajuste o template, revise as variações e publique." actions={<Link href="/studio?step=history" className="cr-button cr-button--secondary cr-control--md"><History size={14} /> Histórico</Link>} className="studio-product-page">
    <StudioStepper current={step} />
    {step === "select" ? <section className="studio-select-layout"><div className="product-panel"><header><h2>Materiais do projeto</h2><Button size="sm" onClick={() => setUploadOpen(true)}><Upload size={13} /> Enviar arquivos</Button></header><div className="product-panel-body studio-media-grid">{["Sara Novo", "Cecilia Novo", "Xanaina Novo", "Produto em uso", "Depoimento", "Cena de apoio"].map((name,index) => { const selected = selectedMedia.includes(name); return <button type="button" key={name} aria-pressed={selected} onClick={() => setSelectedMedia((current) => selected ? current.filter((item) => item !== name) : [...current,name])}><span className={`studio-media-thumb tone-${index % 4}`}><MonitorPlay size={20} />{selected ? <i><Check size={11} /></i> : null}</span><strong>{name}</strong><small>9:16 · {(3.2 + index / 3).toFixed(1)} MB</small></button>;})}<button type="button" className="studio-add-media" onClick={() => setUploadOpen(true)}><ImagePlus size={19} /><strong>Adicionar mídia</strong></button></div></div><aside className="product-panel"><header><h2>Resumo</h2></header><div className="product-panel-body"><div className="product-kpi"><span>Selecionados</span><strong>{selectedMedia.length}</strong></div><div className="product-kpi"><span>Formato</span><strong>9:16</strong></div><div className="product-kpi"><span>Duração estimada</span><strong>24 s</strong></div><label className="product-field">Nome do projeto<input defaultValue="Campanha de setembro" /></label><Link className="cr-button cr-button--primary cr-control--md studio-continue" href="/studio?step=customize">Continuar <ArrowRight size={14} /></Link></div></aside></section> : null}
    {step === "customize" ? <section className="studio-workspace"><aside className="studio-template-rail"><span>Templates</span>{templateFixtures.slice(0,5).map((item) => <button key={item.id} type="button" aria-pressed={selectedTemplate === item.id} onClick={() => setSelectedTemplate(item.id)}><i className={`template-art--${item.tone}`} /><strong>{item.name}</strong><small>{item.duration}</small></button>)}</aside><main className="studio-stage"><div className="studio-video-preview"><span>CREATYE ORIGINAL</span><strong>Transforme uma ideia em movimento.</strong><button type="button" aria-label="Reproduzir"><Play size={20} fill="currentColor" /></button></div><div className="studio-timeline"><div><span style={{width:"72%"}} /><i style={{left:"38%"}} /></div><small>00:09</small><small>00:24</small></div></main><aside className="studio-inspector"><h2>Personalizar</h2><label className="product-field">Título<textarea defaultValue="Transforme uma ideia em movimento." /></label><label className="product-field">Fonte<select><option>Geist Sans</option><option>Geist Mono</option></select></label><label className="product-field">Cor principal<input type="color" defaultValue="#171717" /></label><label className="product-field">Ritmo<select><option>Equilibrado</option><option>Dinâmico</option><option>Calmo</option></select></label><Button onClick={() => setNotice("Variação gerada com os novos ajustes.")}><WandSparkles size={14} /> Gerar variação</Button></aside></section> : null}
    {step === "review" ? <section><div className="studio-review-grid">{["Original", "Direta", "Editorial", "Dinâmica"].map((variant,index) => <article key={variant}><div className={`studio-review-video tone-${index}`}><span>{variant}</span><strong>{index === 0 ? "Transforme uma ideia em movimento." : "Sua próxima campanha começa aqui."}</strong><IconButton label="Reproduzir" variant="surface"><Play size={16} fill="currentColor" /></IconButton></div><footer><label className="product-check"><input type="checkbox" defaultChecked={index < 2} /> Aprovar variação</label><Button size="sm"><Download size={12} /> Baixar</Button></footer></article>)}</div><div className="studio-bottom-actions"><Link className="cr-button cr-button--quiet cr-control--md" href="/studio?step=customize"><ArrowLeft size={14} /> Voltar</Link><Link className="cr-button cr-button--primary cr-control--md" href="/studio?step=publish">Aprovar e publicar <ArrowRight size={14} /></Link></div></section> : null}
    {step === "publish" ? <section className="studio-publish-grid"><div className="product-panel"><header><h2>Destino e legenda</h2></header><div className="product-panel-body studio-form"><label className="product-field">Página<select>{connectedPages.filter((item) => item.status === "active").map((item) => <option key={item.id}>{item.name}</option>)}</select></label><label className="product-field">Legenda<textarea defaultValue="Uma ideia forte merece ganhar movimento. Conheça nosso novo processo criativo. ✦" /></label><label className="product-field">Primeiro comentário<input defaultValue="#creatyestudio #conteudocriativo" /></label><label className="product-check"><input type="checkbox" defaultChecked /> Compartilhar também no Facebook</label></div></div><aside className="product-panel"><header><h2>Agendamento</h2></header><div className="product-panel-body studio-form"><label className="product-field">Data<input type="date" defaultValue="2026-09-24" /></label><label className="product-field">Horário<input type="time" defaultValue="18:30" /></label><label className="product-field">Fuso horário<select><option>Brasília (GMT-3)</option></select></label><Button variant="primary" onClick={() => setNotice("Publicação agendada para 24 de setembro, às 18:30.")}>Agendar publicação</Button><Button onClick={() => setNotice("Conteúdo salvo como rascunho.")}>Salvar rascunho</Button></div></aside></section> : null}
    {uploadOpen ? <ProductModal title="Enviar materiais" description="Adicione vídeos ou imagens ao projeto." onClose={() => setUploadOpen(false)} footer={<><Button variant="quiet" onClick={() => setUploadOpen(false)}>Cancelar</Button><Button variant="primary" onClick={() => { setUploadOpen(false); setNotice("3 arquivos adicionados ao projeto."); }}>Adicionar ao projeto</Button></>}><div className="studio-upload-zone"><Upload size={22} /><strong>Arraste arquivos até aqui</strong><span>MP4, MOV, JPG ou PNG · até 250 MB</span><Button size="sm">Escolher arquivos</Button></div></ProductModal> : null}{notice ? <ProductNotice onClose={() => setNotice("")}>{notice}</ProductNotice> : null}
  </ProductPage>;
}

export function StudioHistory() { const [filter,setFilter]=useState("all"); const items=studioProjects.filter((item)=>filter==="all"||item.status===filter); return <ProductPage eyebrow="Video Studio" title="Histórico" description="Acompanhe rascunhos, renderizações e publicações criadas no Studio." actions={<Link href="/studio?step=select" className="cr-button cr-button--primary cr-control--md"><Plus size={14}/> Novo projeto</Link>}><div className="product-toolbar"><select className="product-compact-select" value={filter} onChange={(event)=>setFilter(event.target.value)}><option value="all">Todos os status</option><option value="draft">Rascunhos</option><option value="scheduled">Agendados</option><option value="published">Publicados</option><option value="failed">Com falha</option></select></div><div className="product-list">{items.map((item)=><Link className="product-row" key={item.id} href="/studio?step=customize"><div><strong>{item.name}</strong><small>{item.type} · {item.format} · {item.destination}</small></div><span className="product-row-meta">{item.updated}</span><span className="product-status" data-status={item.status}>{item.status}</span><ArrowRight size={14}/></Link>)}</div></ProductPage>; }
